# Configuration for librarian-puppet. For example:
# 
# 
# mod "puppetlabs/razor"
# mod "puppetlabs/ntp", "0.0.3"
# 

forge "http://forge.puppetlabs.com"

mod "puppetlabs/postgresql", "3.2.0"

mod "apt", :git => "git://github.com/puppetlabs/puppetlabs-apt.git"

mod "stdlib",
  :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"

