# Configuration for librarian-puppet. For example:
# 
# forge "http://forge.puppetlabs.com"
# 
# mod "puppetlabs/razor"
# mod "puppetlabs/ntp", "0.0.3"
# 

forge "http://forge.puppetlabs.com"
mod "rtyler/jenkins" 
# , :git => "git://github.com/jenkinsci/puppet-jenkins.git"

mod "apt", :git => "git://github.com/puppetlabs/puppetlabs-apt.git"

mod "stdlib",
  :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"

